services:
  - type: web
    name: ai-help-center-backend
    env: python
    region: oregon
    buildCommand: |
      python -V
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: MONGODB_DB_NAME
        value: ai_assistance
      - key: CORS_ORIGINS
        value: '["https://ai-help-center-frontend-vkp9.vercel.app"]'
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: MONGODB_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.7
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1 